import Login from '@/components/login/Login';
import { Metadata } from 'next';
import React from 'react';
  export const metadata :Metadata = {
    title: "university login",
    description: "Generated by next app",
  };
const LoginPage = () => {

  return (
    <div>
      <Login/>
    </div>
  );
};

export default LoginPage;
