import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Providers from "@/lib/Providers";
import StyledComponentsRegistry from "@/lib/AntdRegistry";
import Providers from "@/lib/Providers";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "University Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </body>
      </html>
     </Providers>
  );
}
